SaatSatış/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Models;
using SaatSatış.DAL;

namespace SaatSatış.Controllers
{
    public class LogInController : Controller
    {
        // GET: LogIn
        WatchContext db = new WatchContext();
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = Md5(user.Password);
               
                if(user.Status == null)
                {
                    user.Status = "User";
                }
                db.Users.Add(user);   
                db.SaveChanges();
                return RedirectToAction("Index", "Front");
            }else
                return View();
        }
        public ActionResult LogInPartial()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult LogInPartial(string userName, string pass="")
        {
            string password = Md5(pass);
            User user = db.Users.Where(u => u.UserName == userName && u.Password == password).SingleOrDefault();
            if (user != null && user.Status == "Admin")
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                Session["UserID"] = user.UserID;
                Session["UserName"] = user.UserName;
                Session.Timeout = 2;
                return RedirectToAction("Index", "Watches");
            }
            else if (user != null && user.Status == "User")
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                Session["UserID"] = user.UserID;
                Session["UserName"] = user.UserName;
                Session.Timeout = 2;
                return RedirectToAction("Index","Front");
            }
            return PartialView();
        }
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Front");
        }
        public string Md5(string strSifre)
        {
            MD5 md5 = MD5.Create();
            byte[] hashData = md5.ComputeHash(Encoding.UTF8.GetBytes(strSifre));

            string strHashedPassword = "";
            for (int i = 0; i < hashData.Length; i++)
            {
                strHashedPassword += hashData[i].ToString("x2");
            }
            return strHashedPassword;
        }
    }
}

SaatSatış/Views/Shared/FilterLayout.cshtml
@using SaatSatış.Models
@model SaatSatış.Models.LayoutVM

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="~/Front/Index">Saat</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/Front/FilterByGender?gender=Erkek">Erkek</a></li>
                        <li><a href="/Front/FilterByGender?gender=Kadın">Kadın</a></li>
                        <li><a href="#">Page 1-3</a></li>
                    </ul>
                </li>
                <li><a href="#">Page 2</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#" data-toggle="popover" data-html="true" data-placement="bottom"><span class="glyphicon glyphicon-user"></span>Giriş</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Kayıt Ol</a></li>
            </ul>
        </div>
    </nav>
    <div>@RenderBody()</div>
</body>
</html>

SaatSatış/Views/Shared/FrontLayout.cshtml
@using Models
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div data-spy="affix" data-offset-top="-60" style="z-index:1; width:100%; top:0px;">
        <nav class="navbar navbar-inverse" >
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="~/Front/Index">Saat</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/Front/FilteredWatches?gender=Erkek">Erkek</a></li>
                    <li><a href="/Front/FilteredWatches?gender=Kadın">Kadın</a></li>
                    <li><a href="/Front/FilteredWatches?gender=Çocuk">Çocuk</a></li>
                    
                </ul>
                @if (Session["UserID"] == null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <form class="navbar-form navbar-left" action="~/Front/Search" method="get" autocomplete="off">
                            <div class="form-group">
                                <input type="text" class="form-control" id="search" name="search" placeholder="Arama Yap" value="@ViewData["CurrentFilter"]" />
                            </div>
                            <button type="submit" class="btn btn-default">Ara</button>
                        </form>
                        <li><a href="/Front/Index" onclick="return ajax()" data-toggle="popover" data-placement="bottom"><span class="glyphicon glyphicon-user"></span>Giriş</a></li>
                        <li><a href="/LogIn/SignIn"><span class="glyphicon glyphicon-log-in"></span>Kayıt Ol</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <form class="navbar-form navbar-left" action="~/Front/Search" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" id="search" name="search" placeholder="Arama Yap">
                            </div>
                            <button type="submit" class="btn btn-default">Ara</button>
                        </form>
                        <li><a href="/Front/Cart"><span class="glyphicon glyphicon-shopping-cart"></span>Sepet</a></li>
                        <li><a href="/LogIn/LogOut"><span class="glyphicon glyphicon-log-out"></span>Çıkış</a></li>
                    </ul>
                }
            </div>
        </nav>
        
        
    </div>
    <div style="background-color:aqua; backface-visibility:visible;">@Html.Action("LogInPartial", "LogIn")</div>
    <br />
    <br />
    <div>@RenderBody()</div>

   
 
</body>
</html>
<script>
    function ajax() {
        var lgn = document.getElementById("login")
        if (lgn.style.display == "none")
            lgn.style.display = "block";
        else
            lgn.style.display = "none";
        return false;
    }
</script>

SaatSatış/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div data-spy="affix" data-offset-top="-60" style="z-index:1; width:100%; top:0px;">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="~/Front/Index">Saat</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/Front/FilteredWatches?gender=Erkek">Erkek</a></li>
                    <li><a href="/Front/FilteredWatches?gender=Kadın">Kadın</a></li>
                    <li><a href="/Front/FilteredWatches?gender=Çocuk">Çocuk</a></li>

                </ul>
                @if (Session["UserID"] == null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <form class="navbar-form navbar-left" action="~/Front/Search" method="get" autocomplete="off">
                            <div class="form-group">
                                <input type="text" class="form-control" id="search" name="search" placeholder="Arama Yap" value="@ViewData["CurrentFilter"]" />
                            </div>
                            <button type="submit" class="btn btn-default">Ara</button>
                        </form>
                        <li><a href="/Front/Index" onclick="return ajax()" data-toggle="popover" data-placement="bottom"><span class="glyphicon glyphicon-user"></span>Giriş</a></li>
                        <li><a href="/LogIn/SignIn"><span class="glyphicon glyphicon-log-in"></span>Kayıt Ol</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <form class="navbar-form navbar-left" action="~/Front/Search" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" id="search" name="search" placeholder="Arama Yap">
                            </div>
                            <button type="submit" class="btn btn-default">Ara</button>
                        </form>
                        <li><a href="/Front/Cart"><span class="glyphicon glyphicon-shopping-cart"></span>Sepet</a></li>
                        <li><a href="/LogIn/LogOut"><span class="glyphicon glyphicon-log-out"></span>Çıkış</a></li>
                    </ul>
                }
            </div>
        </nav>
    </div>
 
    <div class="row">
        <div class="col-md-1">
            <br /><br /><br /><br /><br />
            <a href="/Watches/Index" class="list-group-item list-group-item-action">Saatler</a>
            <a href="/Brands/Index/" class="list-group-item list-group-item-action">Markalar</a>
            <a href="/CaseShapes/Index/" class="list-group-item list-group-item-action">Kasa Şekilleri</a>
            <a href="/GlassTypes/Index/" class="list-group-item list-group-item-action">Cam Tipleri</a>
            <a href="/StrapTypes/Index/" class="list-group-item list-group-item-action">Kayış Tipleri</a>
            <a href="/Technologies/Index/" class="list-group-item list-group-item-action">Teknolojiler</a>
            <a href="/Pictures/Index/" class="list-group-item list-group-item-action">Resimler</a>
            <a href="/Colors/Index/" class="list-group-item list-group-item-action">Renkler</a>
            <a href="/Genders/Index/" class="list-group-item list-group-item-action">Cinsiyetler</a>
            <a href="/Users/Index/" class="list-group-item list-group-item-action">Kullanıcılar</a>
        </div>
        <div class="col-md-11">
            <table id="" class="table table-striped">
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                </div>
            </table>
        </div>
    </div>

    
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>