SaatSatış/Controllers/WatchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;
using SaatSatış.DAL;
using SaatSatış.Models;
using SaatSatış.Utility;

namespace SaatSatış.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WatchesController : Controller
    {
        private WatchContext db = new WatchContext();

        // GET: Watches
        public ActionResult Index()
        {
            List<WatchVM> watches = new List<WatchVM>();
            foreach (Watch watch in db.Watches)
            {
                WatchVM watchVM = new WatchVM();
                watchVM.Watch = watch;
                watchVM.Pictures = watch.Pictures;
                watches.Add(watchVM);
            }
            return View(watches.ToList());

        }

        // GET: Watches/Details/5
        public ActionResult Details(int? id)
        {
            WatchVM watchVm = new WatchVM();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Watch watch = db.Watches.Find(id);
            watchVm.Watch = watch;
            watchVm.Pictures = db.Pictures.Where(p => p.WatchID == id).ToList();
            if (watch == null)
            {
                return HttpNotFound();
            }
            return View(watchVm);
        }

        // GET: Watches/Create
        public ActionResult Create()
        {
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName");
            ViewBag.CaseShapeID = new SelectList(db.CaseShapes, "CaseShapeID", "CaseShapeName");
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName");
            ViewBag.GenderID = new SelectList(db.Genders, "GenderID", "GenderName");
            ViewBag.GlassTypeID = new SelectList(db.GlassTypes, "GlassTypeID", "GlassTypeName");
            ViewBag.StrapTypeID = new SelectList(db.StrapTypes, "StrapTypeID", "StrapTypeName");
            ViewBag.TechnologyID = new SelectList(db.Technologies, "TechnologyID", "TechnologyName");
            
            return View();
        }

        // POST: Watches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WatchID,BrandID,WatchModel,ColorID,CaseShapeID,GlassTypeID,StrapTypeID,TechnologyID,GenderID,Price")] Watch watch, HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            if (ModelState.IsValid)
            {
                db.Watches.Add(watch);
                db.SaveChanges();
                int id = db.Watches.Where(w => w.WatchModel == watch.WatchModel).FirstOrDefault().WatchID;

                db.Pictures.Add(new Picture { WatchID = id, PictureName = file1.FileName });
                file1.SaveAs(Server.MapPath(@"\Images\" + file1.FileName));
                Image img = Image.FromFile(Server.MapPath(@"\Images\" + file1.FileName));
                Image imgThumb = img.GetThumbnailImage(150, 150, () => false, IntPtr.Zero);
                imgThumb.Save(Server.MapPath(@"~\Images\ThumbNails\" + file1.FileName));

                db.Pictures.Add(new Picture { WatchID = id, PictureName = file2.FileName });
                file2.SaveAs(Server.MapPath(@"\Images\" + file2.FileName));
                Image img2 = Image.FromFile(Server.MapPath(@"\Images\" + file2.FileName));
                Image imgThumb2 = img.GetThumbnailImage(150, 150, () => false, IntPtr.Zero);
                imgThumb.Save(Server.MapPath(@"~\Images\ThumbNails\" + file2.FileName));

                db.Pictures.Add(new Picture { WatchID = id, PictureName = file3.FileName });
                file3.SaveAs(Server.MapPath(@"\Images\" + file3.FileName));
                Image img3 = Image.FromFile(Server.MapPath(@"\Images\" + file2.FileName));
                Image imgThumb3 = img.GetThumbnailImage(150, 150, () => false, IntPtr.Zero);
                imgThumb.Save(Server.MapPath(@"~\Images\ThumbNails\" + file2.FileName));

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", watch.BrandID);
            ViewBag.CaseShapeID = new SelectList(db.CaseShapes, "CaseShapeID", "CaseShapeName", watch.CaseShapeID);
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", watch.ColorID);
            ViewBag.GenderID = new SelectList(db.Genders, "GenderID", "GenderName", watch.GenderID);
            ViewBag.GlassTypeID = new SelectList(db.GlassTypes, "GlassTypeID", "GlassTypeName", watch.GlassTypeID);
            ViewBag.StrapTypeID = new SelectList(db.StrapTypes, "StrapTypeID", "StrapTypeName", watch.StrapTypeID);
            ViewBag.TechnologyID = new SelectList(db.Technologies, "TechnologyID", "TechnologyName", watch.TechnologyID);
            return View(watch);
        }

        // GET: Watches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Watch watch = db.Watches.Find(id);
            if (watch == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", watch.BrandID);
            ViewBag.CaseShapeID = new SelectList(db.CaseShapes, "CaseShapeID", "CaseShapeName", watch.CaseShapeID);
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", watch.ColorID);
            ViewBag.GenderID = new SelectList(db.Genders, "GenderID", "GenderName", watch.GenderID);
            ViewBag.GlassTypeID = new SelectList(db.GlassTypes, "GlassTypeID", "GlassTypeName", watch.GlassTypeID);
            ViewBag.StrapTypeID = new SelectList(db.StrapTypes, "StrapTypeID", "StrapTypeName", watch.StrapTypeID);
            ViewBag.TechnologyID = new SelectList(db.Technologies, "TechnologyID", "TechnologyName", watch.TechnologyID);
            return View(watch);
        }

        // POST: Watches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WatchID,BrandID,WatchModel,ColorID,CaseShapeID,GlassTypeID,StrapTypeID,TechnologyID,GenderID,Price")] Watch watch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(watch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", watch.BrandID);
            ViewBag.CaseShapeID = new SelectList(db.CaseShapes, "CaseShapeID", "CaseShapeName", watch.CaseShapeID);
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", watch.ColorID);
            ViewBag.GenderID = new SelectList(db.Genders, "GenderID", "GenderName", watch.GenderID);
            ViewBag.GlassTypeID = new SelectList(db.GlassTypes, "GlassTypeID", "GlassTypeName", watch.GlassTypeID);
            ViewBag.StrapTypeID = new SelectList(db.StrapTypes, "StrapTypeID", "StrapTypeName", watch.StrapTypeID);
            ViewBag.TechnologyID = new SelectList(db.Technologies, "TechnologyID", "TechnologyName", watch.TechnologyID);
            return View(watch);
        }

        // GET: Watches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Watch watch = db.Watches.Find(id);
            if (watch == null)
            {
                return HttpNotFound();
            }
            return View(watch);
        }

        // POST: Watches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Watch watch = db.Watches.Find(id);
            db.Watches.Remove(watch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SaatSatış/Views/Watches/Create.cshtml
@model Models.Watch

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Oluştur</h2>


@using (Html.BeginForm("Create", "Watches", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Saat</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BrandID, "BrandID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BrandID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BrandID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WatchModel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WatchModel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WatchModel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ColorID, "ColorID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ColorID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ColorID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CaseShapeID, "CaseShapeID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CaseShapeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CaseShapeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GlassTypeID, "GlassTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GlassTypeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GlassTypeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StrapTypeID, "StrapTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StrapTypeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StrapTypeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TechnologyID, "TechnologyID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TechnologyID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TechnologyID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenderID, "GenderID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GenderID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Pictures, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file1" id="file1" />
            <input type="file" name="file2" id="file2" />
            <input type="file" name="file3" id="file3" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Oluştur" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SaatSatış/Views/Watches/Delete.cshtml
@model Models.Watch

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sil</h2>

<h3>Silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Saat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseShape.CaseShapeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseShape.CaseShapeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.ColorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.ColorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender.GenderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.GenderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GlassType.GlassTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GlassType.GlassTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StrapType.StrapTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StrapType.StrapTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Technology.TechnologyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Technology.TechnologyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WatchModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WatchModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Dön", "Index")
        </div>
    }
</div>

SaatSatış/Views/Watches/Details.cshtml
@model SaatSatış.Models.WatchVM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detaylar</h2>

<div>
    <h4>Saat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Watch.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.CaseShape.CaseShapeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.CaseShape.CaseShapeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.Color.ColorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.Color.ColorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.Gender.GenderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.Gender.GenderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.GlassType.GlassTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.GlassType.GlassTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.StrapType.StrapTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.StrapType.StrapTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.Technology.TechnologyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.Technology.TechnologyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.WatchModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.WatchModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watch.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watch.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pictures)
        </dt>
        <dd>
            <img src="~/Images/ThumbNails/@Model.Pictures.ElementAt(0).PictureName" />
            <img src="~/Images/ThumbNails/@Model.Pictures.ElementAt(1).PictureName" />
            <img src="~/Images/ThumbNails/@Model.Pictures.ElementAt(2).PictureName" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.Watch.WatchID }) |
    @Html.ActionLink("Listeye Dön", "Index")
</p>

SaatSatış/Views/Watches/Edit.cshtml
@model Models.Watch

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Saat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WatchID)

        <div class="form-group">
            @Html.LabelFor(model => model.BrandID, "BrandID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WatchModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WatchModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WatchModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorID, "ColorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaseShapeID, "CaseShapeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CaseShapeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CaseShapeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GlassTypeID, "GlassTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GlassTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GlassTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrapTypeID, "StrapTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StrapTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StrapTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TechnologyID, "TechnologyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TechnologyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TechnologyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderID, "GenderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SaatSatış/Views/Watches/Index.cshtml
@model IEnumerable<SaatSatış.Models.WatchVM>

@{
    ViewBag.Title = "Saatler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Saatler</h2>
<p>
    @Html.ActionLink("Yeni Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Watch.Brand.BrandName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.CaseShape.CaseShapeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.Color.ColorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.Gender.GenderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.GlassType.GlassTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.StrapType.StrapTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.Technology.TechnologyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.WatchModel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Watch.Price)
        </th>
        <th>Resim</th>
        <th>İşlemler</th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.Brand.BrandName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.CaseShape.CaseShapeName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.Color.ColorName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.Gender.GenderName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.GlassType.GlassTypeName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.StrapType.StrapTypeName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.Technology.TechnologyName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.WatchModel)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Watch.Price)
    </td>
    <td>
        <img src="~/Images/ThumbNails/@item.Pictures.ElementAt(0).PictureName" />
    </td>
    <td>
        @Html.ActionLink("Düzenle", "Edit", new { id = item.Watch.WatchID }) <br />
        @Html.ActionLink("Detaylar", "Details", new { id = item.Watch.WatchID }) <br />
        @Html.ActionLink("Sil", "Delete", new { id = item.Watch.WatchID })
    </td>
</tr>
}

</table>